Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyterbook/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyterbook/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyterbook/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyterbook/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyterbook/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyterbook/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyterbook/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyterbook/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
assert same_root(func_0_closure, func_0_der_closure, 0.4, 50, 0.1, 0.1, 10) is False, 'Basic test failed'
assert same_root(func_0_closure, func_0_der_closure, 0.4, 1, 0.1, 0.1, 10) is True, 'Basic test failed'
assert same_root(func_0_closure, func_0_der_closure, 10, 40, 0.1, 0.1, 10) is False, 'Basic test failed'
assert same_root(func_0_closure, func_0_der_closure, 0.4, -1, 0.1, 0.1, 10) is False, 'Basic test failed'

print("Function seems to work")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[20], line 1[0m
[0;32m----> 1[0m [38;5;28;01massert[39;00m same_root(func_0_closure, func_0_der_closure, [38;5;241m0.4[39m, [38;5;241m50[39m, [38;5;241m0.1[39m, [38;5;241m0.1[39m, [38;5;241m10[39m) [38;5;129;01mis[39;00m [38;5;28;01mFalse[39;00m, [38;5;124m'[39m[38;5;124mBasic test failed[39m[38;5;124m'[39m
[1;32m      2[0m [38;5;28;01massert[39;00m same_root(func_0_closure, func_0_der_closure, [38;5;241m0.4[39m, [38;5;241m1[39m, [38;5;241m0.1[39m, [38;5;241m0.1[39m, [38;5;241m10[39m) [38;5;129;01mis[39;00m [38;5;28;01mTrue[39;00m, [38;5;124m'[39m[38;5;124mBasic test failed[39m[38;5;124m'[39m
[1;32m      3[0m [38;5;28;01massert[39;00m same_root(func_0_closure, func_0_der_closure, [38;5;241m10[39m, [38;5;241m40[39m, [38;5;241m0.1[39m, [38;5;241m0.1[39m, [38;5;241m10[39m) [38;5;129;01mis[39;00m [38;5;28;01mFalse[39;00m, [38;5;124m'[39m[38;5;124mBasic test failed[39m[38;5;124m'[39m

[0;31mAssertionError[0m: Basic test failed
AssertionError: Basic test failed

